#!/bin/bash
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
#   $1       $2       $3
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for an sample, or uncomment the next line and
# rename the file to "post-receive".

#. /usr/share/doc/git-core/contrib/hooks/post-receive-email

file_path="MapClient/autobuild/"
file_name="MyDsh.$date_mmdd.swf"
date_mmdd=`date +%m%d%H%M`

cd ..
echo "reset codebase"
git reset --hard -q

script/build-project.sh
script/export-to-server.sh file_path file_name date_mmdd

echo 'end'

